### ISSUE TITLE
Ordered TOC doesn't work

### ISSUE THREAD

**Issue by laowantong** [frnmst/md-toc#17]
The generation of an ordered TOC seems broken. Take for instance the example of the README:

```python
import md_toc

open("test.md", "w").write("""
# this
## is
## a
### foo
#### booo
### foo
## file

## bye

# bye
""")

print(md_toc.build_toc('test.md', ordered=True))
```

Result:

```
AssertionError                            Traceback (most recent call last)
<ipython-input-11-e23380fd2495> in <module>
     15 """)
     16 
---> 17 print(md_toc.build_toc('test.md', ordered=True))

/anaconda3/lib/python3.7/site-packages/md_toc/api.py in build_toc(filename, ordered, no_links, no_indentation, no_list_coherence, keep_header_levels, parser, list_marker, skip_lines)
    228                     compute_toc_line_indentation_spaces(
    229                         header_type_curr, header_type_prev, parser, ordered,
--> 230                         list_marker, indentation_log, index)
    231                     no_of_indentation_spaces_curr = indentation_log[
    232                         header_type_curr]['indentation spaces']

/anaconda3/lib/python3.7/site-packages/md_toc/api.py in compute_toc_line_indentation_spaces(header_type_curr, header_type_prev, parser, ordered, list_marker, indentation_log, index)
    420         if ordered:
    421             assert list_marker in md_parser[parser]['list']['ordered'][
--> 422                 'closing markers']
    423         else:
    424             assert list_marker in md_parser[parser]['list']['unordered'][

AssertionError: 
```

Passing `True` gives the expected result.

Thanks for this work!

**Comment by frnmst** [comment]
Hi,
thank you for reporting this.

Try putting the list marker explicitly:

`print(md_toc.build_toc('test.md', ordered=True, list_marker=')'))`
or
`print(md_toc.build_toc('test.md', ordered=True, list_marker='.'))`

I think that some API changes are needed.

**Comment by laowantong** [comment]
Thank you for your quick reply, it works! The result is not exactly what I expected, though. Is there any option/plan for generating chained numbering, like 2.1.4?

**Comment by frnmst** [comment]
No, unfortunately there is no such option but it might not be too hard to implement.

**Comment by laowantong** [comment]
May be it's a little harder if you renumber back the actual sections. I think this is how the numbering works usually. However, when the Markdown file is versioned, it results in some more noise. So I think I will stick with `ordered=False` for the moment. Thanks! 😸

**Comment by frnmst** [comment]
Ah ok. No problem.

But if you mean like:

```
1.
2.
    2.1.
        2.1.1.
    2.2.
        2.2.1.
```

I'm not even sure it is possible (i.e. interpreted as an ordered list) according to the markdown specifications (see for example https://github.github.com/gfm/#ordered-list).

**Comment by frnmst** [comment]
https://github.com/frnmst/md-toc/commit/ef555d098bc96107dada61dafa4ba2b63eae3186 fixes this issue.
