### ISSUE TITLE
Probably wrong license declaration

### ISSUE THREAD

**Issue by Sakirnth-Z** [frnmst/md-toc#27]
Hello

I have packaged md-toc for Debian, but the package was rejected.
Because some license declaration aren't correct.

I assume that you wanted to use GPLv3+ for these files instead of GPLv5+ which doesn't exist:
asciinema/md_toc_asciinema_1_0_0_demo.sh
asciinema/md_toc_asciinema_2_0_0_demo.sh
asciinema/md_toc_asciinema_3_0_0_demo.sh
asciinema/md_toc_asciinema_3_1_0_demo.sh
asciinema/md_toc_asciinema_5_0_0_demo.sh
asciinema/md_toc_asciinema_6_0_0_demo.sh
asciinema/md_toc_asciinema_7_0_0_demo.sh
asciinema/md_toc_asciinema_7_1_0_demo.sh

When that is the case you can apply the patch, which is in the attachment.
Otherwise please change it to the license which you had in mind.

Thanks and greetings
Sakirnth

[0001-Updating-copyright.patch.txt](https://github.com/frnmst/md-toc/files/6289554/0001-Updating-copyright.patch.txt)

**Comment by frnmst** [comment]
Hello,

Yes it was a typo which was replicated by copy and paste. I have included your patch in the dev branch. Before resubmitting
the package to Debian I would wait for md-toc version 7.2.0 which should be released today or tomorrow, since the patch will be included with it.

Thank you

**Comment by frnmst** [comment]
Done. You can proceed now

**Comment by Sakirnth-Z** [comment]
Thank you very much for the fast fix. I will update it to 7.2.0 in the following days.
