### ISSUE TITLE
Is it possible to ignore certain headers?

### ISSUE THREAD

**Issue by trallnag** [frnmst/md-toc#37]
I'm unable to find anything related to that in the documentation. Is it possible to ignore certain headers?

And thanks for this nice tool

**Comment by frnmst** [comment]
No, it is not currently possible.

How would you identify the headers to ignore:
- by sequential id (easy)
- by content (exact match, regex, ?)
- ?

**Comment by trallnag** [comment]
> No, it is not currently possible.

Okay, good to know

> How would you identify the headers to ignore:

Some similar tools I know exclude headers that contain a certain string. Or header that have a certain string right before the header.

For example <https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one>

> Add `<!-- omit in toc -->` at the end of a heading to ignore it in TOC (It can also be placed above a heading)
