### ISSUE TITLE
Feature request: bring back `build_toc`

### ISSUE THREAD

**Issue by dharmab** [frnmst/md-toc#9]
Building the TOC for a single file used to be really easy:

```python
index[filename] = md_toc.build_toc(filename, keep_header_levels=6, parser='github')
```

Now you have to awkwardly wrap everything in lists:

```
index[filename] = md_toc.build_multiple_tocs([filename], keep_header_levels=6, parser='github')[0]
```

**Comment by frnmst** [comment]
Makes sense. Should be fixed now. See and try: https://github.com/frnmst/md-toc/commit/ef68c4d9e4105c2715ab74d469be0e056a8f6ee0
